-- =============================================================================
-- 007 — Calls and call recordings
--
-- One row per call attempt, whichever way the call was placed. The `channel`
-- and `source` columns record *how* the row came to exist, which matters more
-- than it looks: a duration read from the Android call log is measured, one
-- typed into a post-call sheet on iOS is self-reported, and a report that mixes
-- them without saying so is misleading. See the telecalling-spec skill for why
-- both paths exist and why on-device recording does not.
-- =============================================================================

CREATE TABLE IF NOT EXISTS calls (
  id                BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,

  -- Idempotency key generated by the mobile app before the call is attempted.
  -- The offline queue retries on an ambiguous timeout, and without this a
  -- flaky connection inflates every telecaller's call count.
  client_uuid       CHAR(36)        NULL,

  -- NULL when a telecaller calls, or is called by, a number that matches no
  -- lead. Those calls still belong in the record — the spec asks for incoming
  -- and missed calls, and a customer ringing back from a second handset is
  -- exactly the case worth catching.
  lead_id           BIGINT UNSIGNED NULL,
  user_id           BIGINT UNSIGNED NOT NULL,
  phone             VARCHAR(20)     NOT NULL,

  direction         ENUM('outgoing','incoming') NOT NULL DEFAULT 'outgoing',
  outcome           ENUM('answered','missed','rejected','busy','unreachable','no_answer') NOT NULL,

  -- 'device' = dialled by the handset's own dialler. 'cloud' = bridged by a
  -- telephony provider. Both write this same table, so adding the cloud path
  -- later needs no schema change and no reporting rewrite.
  channel           ENUM('device','cloud') NOT NULL DEFAULT 'device',

  -- Where the numbers came from. 'call_log' is read from the Android call log,
  -- 'manual' is confirmed by the telecaller (the only option on iOS),
  -- 'provider' is a telephony webhook.
  source            ENUM('call_log','manual','provider') NOT NULL DEFAULT 'manual',

  duration_seconds  INT UNSIGNED    NOT NULL DEFAULT 0,
  started_at        DATETIME        NOT NULL,
  ended_at          DATETIME        NULL,

  -- Whether a missed or rejected call has since been dealt with (spec: Module 7
  -- asks to track exactly this). Meaningless for answered calls and ignored
  -- there.
  followed_up       TINYINT(1)      NOT NULL DEFAULT 0,

  -- Provider's own call identifier, so a recording webhook arriving minutes
  -- later can find its row.
  provider_call_sid VARCHAR(120)    NULL,

  created_at        TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY (id),
  UNIQUE KEY uq_calls_client_uuid (client_uuid),
  UNIQUE KEY uq_calls_provider_sid (provider_call_sid),

  -- The lead's call history, and the timeline.
  KEY idx_calls_lead (lead_id, started_at),
  -- "My calls today" on mobile, and per-employee call monitoring on admin.
  KEY idx_calls_user_started (user_id, started_at),
  -- Answered-vs-missed reporting, per employee, over a date range.
  KEY idx_calls_user_outcome (user_id, outcome, started_at),
  -- Admin call monitoring, newest first, and daily/weekly/monthly rollups.
  KEY idx_calls_started (started_at),
  -- The missed-call queue: unresolved misses for one employee.
  KEY idx_calls_followup_queue (user_id, outcome, followed_up),

  CONSTRAINT fk_calls_lead
    FOREIGN KEY (lead_id) REFERENCES leads (id) ON DELETE SET NULL,
  CONSTRAINT fk_calls_user
    FOREIGN KEY (user_id) REFERENCES telecaller_users (id) ON DELETE CASCADE
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- =============================================================================
-- Call recordings
--
-- A separate table, not columns on `calls`, for two reasons: the overwhelming
-- majority of calls will never have one, and access to recordings is audited
-- and permission-gated separately from access to call metadata.
--
-- `storage_key` is opaque — a filename under the local driver, an object key
-- under S3 — and is resolved only by services/storage. Recordings are served
-- exclusively through an authenticated route that issues a short-lived
-- presigned URL. There is no public URL for call audio.
-- =============================================================================

CREATE TABLE IF NOT EXISTS call_recordings (
  id               BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  call_id          BIGINT UNSIGNED NOT NULL,
  lead_id          BIGINT UNSIGNED NULL,
  user_id          BIGINT UNSIGNED NULL,

  storage_key      VARCHAR(255)    NOT NULL,
  mime_type        VARCHAR(100)    NOT NULL DEFAULT 'audio/mpeg',
  size_bytes       BIGINT UNSIGNED NOT NULL DEFAULT 0,
  duration_seconds INT UNSIGNED    NOT NULL DEFAULT 0,

  -- Which mechanism produced the file. 'device' is reserved and unused for now:
  -- Android 10+ and every iOS version block third-party call recording, so in
  -- practice recordings arrive from a telephony provider.
  origin           ENUM('device','cloud') NOT NULL DEFAULT 'cloud',
  provider         VARCHAR(40)     NULL,

  uploaded_at      DATETIME        NULL,
  created_at       TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY (id),
  UNIQUE KEY uq_call_recordings_call (call_id),
  UNIQUE KEY uq_call_recordings_key (storage_key),
  KEY idx_call_recordings_lead (lead_id, created_at),
  KEY idx_call_recordings_user (user_id, created_at),
  KEY idx_call_recordings_created (created_at),

  CONSTRAINT fk_call_recordings_call
    FOREIGN KEY (call_id) REFERENCES calls (id) ON DELETE CASCADE,
  CONSTRAINT fk_call_recordings_lead
    FOREIGN KEY (lead_id) REFERENCES leads (id) ON DELETE SET NULL,
  CONSTRAINT fk_call_recordings_user
    FOREIGN KEY (user_id) REFERENCES telecaller_users (id) ON DELETE SET NULL
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;
