import { assetPath } from '@/lib/paths';

/**
 * A responsive photograph.
 *
 * Every image on the site goes through here so the same three things are always true:
 *
 *   - WebP is served with the original JPEG as a fallback. The variants are generated
 *     ahead of time and committed, rather than converted at build or request time —
 *     `output: 'export'` means there is no image server in production, and adding a
 *     native encoder to the build would be a heavy dependency for assets that change
 *     a handful of times a year.
 *
 *   - `srcSet` and `sizes` are always supplied together. `srcSet` alone lets the
 *     browser assume the image spans the full viewport, which is how a card thumbnail
 *     ends up downloading the 1280px file.
 *
 *   - Intrinsic `width`/`height` are always set, so the browser reserves the right box
 *     before the bytes arrive and the page does not jump as photographs load.
 *
 * Loading is lazy by default and must be opted out of for anything above the fold,
 * where lazy loading delays the largest contentful paint instead of helping it.
 */

/** The widths generated by the optimisation step. */
const VARIANTS = [480, 800, 1280] as const;

type PhotoProps = {
  /** Path under `public/`, e.g. `/images/gallery/academy-cad-workstation.jpg`. */
  src: string;
  /** What the photograph shows. Never the file name, never a keyword list. */
  alt: string;
  width: number;
  height: number;
  /** Layout width at each breakpoint — required for the browser to pick sensibly. */
  sizes: string;
  className?: string;
  /** Set for above-the-fold images; everything else stays lazy. */
  priority?: boolean;
};

export function Photo({ src, alt, width, height, sizes, className, priority = false }: PhotoProps) {
  const base = src.replace(/\.(jpe?g|png)$/i, '');
  const srcSet = VARIANTS.map((w) => `${assetPath(`${base}-${w}.webp`)} ${w}w`).join(', ');

  return (
    <picture>
      <source type="image/webp" srcSet={srcSet} sizes={sizes} />
      <img
        className={className}
        src={assetPath(src)}
        alt={alt}
        width={width}
        height={height}
        sizes={sizes}
        loading={priority ? 'eager' : 'lazy'}
        // `high` on the hero tells the browser to fetch it before lazy images below.
        fetchPriority={priority ? 'high' : 'auto'}
        decoding={priority ? 'sync' : 'async'}
      />
    </picture>
  );
}
