import type { CSSProperties } from 'react';
import { assetPath } from '@/lib/paths';

/**
 * A responsive photograph.
 *
 * Every image on the site goes through here so the same three things are always true:
 *
 *   - WebP is served with the original JPEG as a fallback. The variants are generated
 *     ahead of time and committed, rather than converted at build or request time —
 *     `output: 'export'` means there is no image server in production, and adding a
 *     native encoder to the build would be a heavy dependency for assets that change
 *     a handful of times a year.
 *
 *   - `srcSet` and `sizes` are always supplied together. `srcSet` alone lets the
 *     browser assume the image spans the full viewport, which is how a card thumbnail
 *     ends up downloading the 1280px file.
 *
 *   - Intrinsic `width`/`height` are always set, so the browser reserves the right box
 *     before the bytes arrive and the page does not jump as photographs load.
 *
 * Loading is lazy by default and must be opted out of for anything above the fold,
 * where lazy loading delays the largest contentful paint instead of helping it.
 */

/** Widths generated by the optimisation step for ordinary in-page imagery. */
const CARD_VARIANTS = [480, 800, 1280];

/** Full-bleed imagery needs larger steps; a 1280px file stretched across a 1920px
    hero is visibly soft. */
export const HERO_VARIANTS = [640, 1024, 1440, 1920];

type PhotoProps = {
  /** Path under `public/`, e.g. `/images/gallery/academy-cad-workstation.jpg`. */
  src: string;
  /** What the photograph shows. Never the file name, never a keyword list. */
  alt: string;
  width: number;
  height: number;
  /** Layout width at each breakpoint — required for the browser to pick sensibly. */
  sizes: string;
  className?: string;
  /** Set for above-the-fold images; everything else stays lazy. */
  priority?: boolean;
  /** Override the generated widths, e.g. `HERO_VARIANTS` for a full-bleed image. */
  variants?: number[];
  /**
   * Inline style on the `<img>`. Used for per-image `object-position`, which is a
   * property of the photograph — where its subject sits in the frame — rather than of
   * the layout, so it belongs with the image data and not in a stylesheet class.
   */
  style?: CSSProperties;
};

export function Photo({
  src,
  alt,
  width,
  height,
  sizes,
  className,
  priority = false,
  variants = CARD_VARIANTS,
  style,
}: PhotoProps) {
  const base = src.replace(/\.(jpe?g|png)$/i, '');
  const srcSet = variants.map((w) => `${assetPath(`${base}-${w}.webp`)} ${w}w`).join(', ');

  return (
    <picture>
      <source type="image/webp" srcSet={srcSet} sizes={sizes} />
      <img
        className={className}
        src={assetPath(src)}
        alt={alt}
        style={style}
        width={width}
        height={height}
        sizes={sizes}
        loading={priority ? 'eager' : 'lazy'}
        // `high` on the hero tells the browser to fetch it before lazy images below.
        fetchPriority={priority ? 'high' : 'auto'}
        decoding={priority ? 'sync' : 'async'}
      />
    </picture>
  );
}
